version: '2'
services:
  zoo:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888
  nifi1-dc1:
    image: apache/nifi:1.8.0
    ports:
      - 8088    
    environment:
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=9999
      - NIFI_ZK_CONNECT_STRING=zoo:2181
      - NIFI_ZK_ROOT_NODE=/nifidc1
    depends_on:
      - zoo
  nifi2-dc1:
    image: apache/nifi:1.8.0
    ports:
      - 8080   
    environment:
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=9999
      - NIFI_ZK_CONNECT_STRING=zoo:2181
      - NIFI_ZK_ROOT_NODE=/nifidc1
    depends_on:
      - zoo
  nifi3-dc1:
    image: apache/nifi:1.8.0
    ports:
      - 8080    
    environment:
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=9999
      - NIFI_ZK_CONNECT_STRING=zoo:2181
      - NIFI_ZK_ROOT_NODE=/nifidc1
    depends_on:
      - zoo   
  nifi1-dc2:
    image: apache/nifi:1.8.0
    ports:
      - 8088    
    environment:
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=9999
      - NIFI_ZK_CONNECT_STRING=zoo:2181
      - NIFI_ZK_ROOT_NODE=/nifidc2
    depends_on:
      - zoo
  nifi2-dc2:
    image: apache/nifi:1.8.0
    ports:
      - 8080   
    environment:
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=9999
      - NIFI_ZK_CONNECT_STRING=zoo:2181
      - NIFI_ZK_ROOT_NODE=/nifidc2
    depends_on:
      - zoo
  nifi3-dc2:
    image: apache/nifi:1.8.0
    ports:
      - 8080    
    environment:
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=9999
      - NIFI_ZK_CONNECT_STRING=zoo:2181
      - NIFI_ZK_ROOT_NODE=/nifidc2
    depends_on:
      - zoo         